[package]
name = "vibe-action"
version = "0.1.4"
edition = "2024"
license = "Apache-2.0"
description = "Command router — execute shell commands and LLM prompts via simple YAML actions."
repository = "https://gitcode.com/keygenqt_vz/vibe-action"
documentation = "https://vibe-action.keygenqt.com"
authors = ["Vitaliy Zarubin <keygenqt@yandex.ru>"]
keywords = ["cli", "llm", "pipeline", "automation"]
readme = "README.md"

[dependencies]
# fix
zune-jpeg = { version = "0.5", features = ["log"] }

# CLI
clap = { version = "4.6", features = ["derive", "string"] }
clap-cargo = "0.18"
colored = "3.1"
inquire = "0.9.4"

# Async runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# Http client
reqwest = { version = "0.13", features = ["json"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
yaml_serde = "0.10"
serde_toon = "0.2"
json5 = "1.3"
toml = "1.1.2"
xml = "1.2"
serde-xml-rs = "0.8"

# Utilities
dirs = "6"
anyhow = "1"
chrono = "0.4"
regex = "1.10"
dunce = "1"
walkdir = "2.5"
url = "2.5"
arboard = "3.6"
shell-words = "1.1"
notify-rust = "4"
tiktoken-rs = "0.12"
termimad = "0.34"
syntect = "5.3"
two-face = "0.5.1"
image = "0.25"
base64 = "0.22"
md5 = "0.8"
html2text = "0.17"
pdf-extract = "0.12"
mime2ext = "0.1.54"
hostname = "0.4.2"
indexmap = { version = "2", features = ["serde"] }
fs2 = "0.4.3"
libc = "0.2"
sysinfo = "0.38"

# Debug logging (--debug flag)
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Vibe
vibe-cluster = "0.0.6"
vibe-ast = "0.0.13"
vibe-fs = "0.0.4"
