# Controls how imports are grouped.
# NOTE: This option is only available on the nightly Rust channel.
# Usage: rustup run nightly cargo fmt
imports_granularity = "Item"

# Update version:
# Install: cargo install --path . --force
# Update changelog: git cliff --tag v0.4.1 -o CHANGELOG.md
# Create tag: git tag v0.4.1 / git push --tags / cargo publish
